bellshade/PHP

basic/array_search.php
MENCARI DATA DALAM ARRAY
Pembahasan :
- Mencari data berdasarkan key / index
- Mencari data berdasarkan value
=> add: array_search - mencari data dalam array

CONTRIBUTING.md
Halo,
Izin menuliskan contributing.md sebagai panduan / pedoman agar teman-teman yang mau berkontribusi dapat selaras dengan kontributor-kontributor lainnya. 
Silahkan direview docs-team, php-team dan owner juga.
=> docs: menambahkan contributing.md

basics/array/array_basic.php
Menambah `array_basic` untuk pembahasan tentang dasar tipe data array dalam PHP
=> add: array_basic - Dasar tipe data array

CONTRIBUTING.md, algorithms/BackTracking/PathFinding.php, algorithms/index.php, tests/BackTracking/PathFindingTest.php
Perubahan: 
- Menambahkan algoritma baru: Algoritma Backtracking untuk implementasi Pathfinding
- Memperbaiki kesalahan template unit testing pada contribution.md
- Memperjelas petunjuk kontribusi: Menampilkan langsung di method dibolehkan asal untuk kebutuhan visualisasi / penjelas algoritma.
=> Added algoritma, fix contribution.md

CONTRIBUTING.md, basics/array/array_basic.php
Memperbaiki komentar (penjelasan) dalam kode, seperti typo, susunan dan beberapa perbaikan kecil lainnya.
=> fix: Memperbaiki komentar (penjelasan) dan perbaikan kecil lainnya.

basics/datetime/datetime_basic.php
Saya menambahkan materi dasar (basics) tentang cara penggunaan datetime basic. Di implementasi kode ini terdapat berbagai cara menampilkan DateTime dan mengatur DateTime lengkap dengan penjelasan dokumentasi kode yang mudah di mengerti.
=> add: basic - cara penggunaan datetime

basics/loop/recursive_loop.php
Gue nambahin jenis pengulangan secara rekursif
=> Add recursive loop.php

basics/3_operator/3_comparison_operator.php, basics/3_operator/README.md
Menindak lanjuti tentang perubahan gaya folder, jadi saya coba mencoba untuk memberikan *sedikit sentuhan awal* sekaligus *pemanasan* untuk bagian basic/operator algorithm sesuai referensi dari issue #15.
Mohon untuk tindak lanjutnya para maintener, trims.
=> Refactoring folder basic dan tambahkan operator/comparison_operator

basics/3_operator/4_logical_operator.php, basics/3_operator/README.md
References: #15
Masih menyicil dulu *karena kebetulan ini hacktoberfest*, ada beberapa yang saya tambahkan di basics/operator yaitu:
- `OS` = GNU/Linux Manjaro x86_64
@bellshade/php-team
=> Menambah operator logical di basic/operator

basics/4_conditional_statements/1_if_elseif_else.php, basics/4_conditional_statements/2_switch.php, basics/4_conditional_statements/README.md, basics/4_conditional_statements/index.php
Closes #16
saya menggunakan (im using):
Mohon Reviewnya :pray:  : 
@bellshade/php-team 
=> add: Menambahkan materi pengkondisian

README.md
Closes 
saya menggunakan (im used):
=> docs: menyunting README.md

.mergify.yml
update bot mencakup:
- mengucapkan terima kasih ketika label ``ready-to-merge``
- mengganti beberapa nama pada bot
- mengganti cek workflow karena tidak terdeteksi ketika passed test
- menambahkan label ``sudah direview !``
contoh demo bot  [ merge pada pull request java ](https://github.com/bellshade/Java/pull/58) yang sudah di update untuk testing
tidak menggunakan testing untuk yaml file
=> feat: update bot

basics/12_database_dasar_prosedural/4_mysqli_fetch.php, basics/12_database_dasar_prosedural/README.md
Closes #99 
- `os` = `Windows 11`
- `web server` = `apache`
- `PHP version` = `PHP 7.4`
- `stack env` = `Yes, Laragon`
- `base url` = `bellshade.test/php-forked/ (sub directory)`
> Mention tidak dilakukan untuk percobaan otomasi workflow PR
> **Keterangan:** coba ikuti langkah-langkah yang ada di `README.md` untuk menjalankan demonya
> Di titik ini, seharusnya sudah terbentuk database dan beberapa sampel data yang sudah ada didalam tabel. Cek issue #98  untuk informasi selengkapnya atau baca `README.md` bagian membuat tabel
=> Menambahkan sub-materi mengambil data pada materi database dasar

.mergify.yml
setting ke min approval 2 maintainer atau 2 reviewer
tidak ada testing pada yaml file
=> fix: set min approval 2 orang

basics/11_cookie_dan_session/1_set_session.php, basics/11_cookie_dan_session/2_get_session.php, basics/11_cookie_dan_session/3_update_session.php, basics/11_cookie_dan_session/4_delete_session.php, basics/11_cookie_dan_session/5_set_cookie.php, basics/11_cookie_dan_session/6_update_cookie.php, basics/11_cookie_dan_session/7_delete_cookie.php, basics/11_cookie_dan_session/README.md
=> add: Menambah Materi Session dan Cookie

basics/14_oop_dasar/README.md
Saya melakukan penyederhanaan submateri class dan object pada materi oop dasar. Hal ini dilakukan agar dapat tetap selaras dan konsisten dengan sub materi berikutnya dan juga sebelumnya. Dilakukan simplifikasi dengan harapan tidak akan membuat para pembaca bingung dengan teks yang panjang melihat materi OOP bakal menjadi kompleks seiiring materi-materi berikutnya berjalan.
- `os` = `win11`
- `webserver` = `laragon`
- `php-ver` = `7.4`
=> docs: simplifikasi materi class dan object

basics/14_oop_dasar/3_property_and_method.php, basics/14_oop_dasar/README.md, env
=> add: Menambahkan Materi Property dan Method

assets/content/basics/10_file_handling/file_handling.txt, basics/10_file_handling/1_membaca_file_dan_folder.php, basics/10_file_handling/README.md
=> add: Menambahkan Membaca File dan Folder

basics/6_manipulasi_string/6_manipulasi_string.php, basics/6_manipulasi_string/README.md
Closes  #17 
- `os` = `windows `
=> fix: Memperbaiki dan Menambahkan Materi Manipulasi String

basics/10_file_handling/3_write_file.php, basics/10_file_handling/README.md
=> add: Menambahkan Materi Write File

basics/14_oop_dasar/4_constructor_destructor.php, basics/14_oop_dasar/4_constructor_destructor2.php, basics/14_oop_dasar/README.md
Closes #110 
- `phpver` = `8.1.2`
- `webserver` = `apache`
=> Menambahkan Basic Materi: Constructor destructor

basics/9_form_handling/4_datetime.php, basics/9_form_handling/README.md
=> add: Menambahkan Materi Form Handling datetime

basics/9_form_handling/5_checkbox.php, basics/9_form_handling/README.md
=> add: Menambahkan Materi Form Handling checkbox

basics/14_oop_dasar/5_property_dan_method_static.php, basics/14_oop_dasar/README.md
Closes #111 
- `phpver` = `8.1.2`
- `webserver` = `apache`
=> Property method static

basics/9_form_handling/6_radio.php, basics/9_form_handling/README.md
=> add: Menambahkan Materi Form Handling radio

basics/9_form_handling/7_file.php, basics/9_form_handling/README.md
=> add: Menambahkan Materi Form Handling File

basics/9_form_handling/8_multiple_file.php, basics/9_form_handling/README.md
=> add: Menambahkan Materi Multiple File untuk Form Handling

basics/10_file_handling/4_delete_file.php, basics/10_file_handling/README.md
=> add: Menambahkan Materi Menghapus File

basics/10_file_handling/5_upload_file.php, basics/10_file_handling/README.md
=> add: Menambahkan Materi Upload File

basics/10_file_handling/6_validation_file.php, basics/10_file_handling/README.md
=> add: Menambahkan Materi File Validation

utilities/SImple_UnitTest/README.md, utilities/SImple_UnitTest/SimpleTest.php, utilities/SImple_UnitTest/WordCount.php, utilities/SImple_UnitTest/composer.json, utilities/SImple_UnitTest/composer.lock
=> add: utilities/SImple_UnitTest/

README.md
Closes 
Saya lihat nama filenya di root projecknya adalah `.env.example` dan bukan `env`, mungkun `env` adalah nama yang dulu dan di dokumentasinya lupa diubah nama filenya, di pr ini saya merubah nama file tersebut di dokumentasi menjadi sesuai yang ada di root foldernya, yaitu `.env.example` dan bukan `env`
**maintainer dokumentasi**
=> docs: mengubah nama file "env" menjadi ".env.example"

.github/pull_request_template.md
=> docs: memperbaiki typo dari "mereiview" ke "mereview"

CONTRIBUTING.md
Closes 
Saya sudah memperbaiki beberapa link anchor yang salah, sehingga sekarang [judul-judul di "Daftar Isi"nya](https://github.com/mushlih-almubarak/PHP/blob/memperbaiki-dokumentasi/CONTRIBUTING.md) bisa di klik dan langsung mengarah ke bagian yang sesuai, sebelum ini ada [beberapa judul yang tidak bisa diklik](https://github.com/bellshade/PHP/blob/main/CONTRIBUTING.md) dan sekarang sudah saya perbaiki.
=> Memperbaiki beberapa kesalahan anchor link di CONTRIBUTING.md

basics/15_oop_lanjutan/1_inheritance.php, basics/15_oop_lanjutan/1_inheritance_Hewan.php, basics/15_oop_lanjutan/1_inheritance_Kucing.php, basics/15_oop_lanjutan/README.md
=> add: Menambahkan Materi Inheritance

basics/15_oop_lanjutan/2_object_type.php, basics/15_oop_lanjutan/README.md
=> add: Menambahkan Materi Object Type

basics/15_oop_lanjutan/1_inheritance_Hewan.php, basics/15_oop_lanjutan/4_overriding_and_final.php, basics/15_oop_lanjutan/README.md
=> add: Menambahkan Materi Overriding and Final

utilities/simple_curl/README.md, utilities/simple_curl/curl.php, utilities/simple_curl/prayogaea.php
=> add: utilities/simple_curl/

utilities/README.md
=> docs: utilities/README.md

README.md
Saya sudah memperbaiki sedikit penulisan EYD yang salah, karena setelah tanda (.) harusnya adalah huruf kapital.
**maintainer dokumentasi**
=> docs: memperbaiki penulisan README

utilities/random_password/generate.php, utilities/random_password/readme.md
=> Menambahkan utilitas untuk membuat password acak/random

basics/14_oop_dasar/6_constant_magic_constants.php, basics/14_oop_dasar/6_constant_magic_constants2.php, basics/14_oop_dasar/6_constant_magic_constants2a.php, basics/14_oop_dasar/6_constant_magic_constants2b.php, basics/14_oop_dasar/6_constant_magic_constants3.php, basics/14_oop_dasar/README.md
Closes #140 
- `os` = `Windows 10`
- `PHP` = `8.2`
=> 14.6. constant dan magic constants

.github/workflows/markdown-linter.yml, .gitignore, .markdownlint.json, .markdownlintignore, package-lock.json, package.json
Closes #195 
Saya menambahkan GitHub Actions untuk memeriksa _file_ berekstensi `*.md` sesuai dengan diskusi pada #195.
Dengan penambahan ini, _file-file_ yang ada saat ini tentu saja tidak akan lulus pemeriksaan. Untuk menjaga fokus dari PR ini, perbaikan _file_ markdown yang ada akan diselesaikan pada PR selanjutnya.
- `os` = `Windows 10`
=> add: CI linter file untuk markdown
